# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work -sv -timescale 1ns/1ps -mfcu +acc  /home/emnalo/Test/ForceDepositReleaseTEST/iverilog/GenericComponent.v /home/emnalo/Test/ForceDepositReleaseTEST/iverilog/Inversor.v
vsim  -onfinish exit -pli /home/emnalo/.local/lib/python3.10/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   sim_build/work.GenericComponent
onbreak resume
run -all
quit
