vcom reg_w.vhd
vcom reg_s.vhd
vcom reg_pc.vhd
vcom reg_io.vhd
vcom reg_inst.vhd
vcom reg_fsr.vhd
vcom reg_file.vhd
vcom reg_cons.vhd
vcom reg_8t.vhd
vcom reg_8rst.vhd
vcom pic_rom.vhd
vcom pic_ctrl.vhd
vcom half_adder.vhd
vcom sumador.vhd
vcom operadores_y_puertas.vhd
vcom pic_alu.vhd
vcom fadr_mux.vhd
vcom pic_core.vhd
vcom bench.vhd
