TOPLEVEL_LANG=verilog
VERILOG_SOURCES +=~/Test/UNITTESTINGAUTO/ICARUS/infra/source/ArithmeticLogicUnit.v
VERILOG_SOURCES +=~/Test/UNITTESTINGAUTO/ICARUS/infra/source/RegisterNbits.v
VERILOG_SOURCES +=~/Test/UNITTESTINGAUTO/ICARUS/infra/source/RegisteredALU.v
VERILOG_SOURCES +=~/Test/UNITTESTINGAUTO/ICARUS/infra/source/RegisteredALU_tb.v
TOPLEVEL =RegisteredALU_tb
MODULE =ParametricTest
include $(shell cocotb-config --makefiles)/Makefile.sim
#make SIM=icarus
