# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vcom -work work +acc /home/emnalo/cocotb-tfm/Processors/usimplez_16_bits/QUESTA-VHDL/GoldenRun/source/Test_Bench.vhd /home/emnalo/cocotb-tfm/Processors/usimplez_16_bits/QUESTA-VHDL/GoldenRun/source/components.vhd /home/emnalo/cocotb-tfm/Processors/usimplez_16_bits/QUESTA-VHDL/GoldenRun/source/usimplez_cpu.vhd /home/emnalo/cocotb-tfm/Processors/usimplez_16_bits/QUESTA-VHDL/GoldenRun/source/usimplez_ram.vhd /home/emnalo/cocotb-tfm/Processors/usimplez_16_bits/QUESTA-VHDL/GoldenRun/source/usimplez_top.vhd
vsim  -onfinish exit -t 1ps -foreign "cocotb_init /home/emnalo/.local/lib/python3.10/site-packages/cocotb/libs/libcocotbfli_modelsim.so"   sim_build/work.bench
log -recursive /*
onbreak resume
run -all
quit
