# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work -sv -timescale 1ns/1ps -mfcu +acc  /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/fadr_mux.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/pic_alu.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_8rst.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_8t.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_cons.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_file.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_fsr.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_inst.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_io.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_pc.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_s.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/reg_w.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/pic_core.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/pic_ctrl.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/pic_rom.v /home/emnalo/cocotb-tfm/Processors/PICStructural/QUESTA-VERILOG/GoldenRun/source/bench.v
vsim  -onfinish exit -pli /home/emnalo/.local/lib/python3.10/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   sim_build/work.bench
log -recursive /*
onbreak resume
run -all
quit
