TOPLEVEL_LANG=verilog
VERILOG_SOURCES +=$(shell pwd)/GenericComponent.v
VERILOG_SOURCES +=$(shell pwd)/Inversor.v
TOPLEVEL = GenericComponent
MODULE = ForceTest
include $(shell cocotb-config --makefiles)/Makefile.sim
#make SIM=icarus

